function [j] = J_CosOGSE(lambda, sequence)
%J_COSOGSE Compute the quantity J(lambda_n, f) for CosOGSE sequence
%
%   lambda: double
%   sequence: Sequence class
%
%   j: double


d = sequence.delta;
D = sequence.Delta;
n = sequence.nperiod;

if lambda < 1e-7
    % Use Taylor expansion when lambda is close to 0 
    % to improve numerical stability
    j = lambda ...
        - lambda^3 * d^2 * 3 / (4 * (n*pi)^2) ...
        + lambda^5 * (12*D*n^2*pi^2*d^3 + 15*d^4 - 4*n^2*pi^2*d^4) / (48 * n^4 * pi^4) ...
        - lambda^6 * D^2 * d^3 / (8 * (n*pi)^2);
else
    j = 4 * n^2 * pi^2 * lambda * ( ...
        - exp(-lambda * (D+d)) * lambda * d ...
        - exp(-lambda * (D-d)) * lambda * d ...
        + 2 * exp(-lambda * D) * lambda * d ...
        + 2 * exp(-lambda * d) * lambda * d ...
        + 4 * n^2 * pi^2 ...
        + (lambda * d - 2) * lambda * d ) ...
        / (4*n^2*pi^2 + lambda^2*d^2)^2;
end
end

